seed: 1234

data:
  name: LOGO_30K
  dataroot: /amax/xyf/data/LOGO/
  img_size: 256

dataloader:
  num_workers: 4
  pin_memory: true
  prefetch_factor: 2
  micro_batch: 0

model:
  mpn:
    base_n_channels: 64
    neck_n_channels: 128
  rin:
    base_n_channels: 32
    neck_n_channels: 128

train:
  n_steps: 40000
  batch_size: 4
  pretrained: ~
  resume: ~
  print_freq: 100
  save_freq: 5000
  eval_freq: 1000
  sample_freq: 1000

  coef_rec: 1.4
  coef_semantic: 0.0001
  coef_idmrf: 0.001
  coef_adv: 0.001
  coef_mpn: 2.0

  optim_mpn:
    lr: 0.00001
    betas: [0.5, 0.9]
  optim_rin:
    lr: 0.00001
    betas: [0.5, 0.9]
  optim_disc:
    lr: 0.00001
    betas: [0.5, 0.9]
